<!DOCTYPE html>
<html>
<head>
<title>BackShop</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<link href='https://fonts.googleapis.com/css?family=Archivo+Narrow:400,700' rel='stylesheet' type='text/css'>


<!-- jQuery -->
<script src="https://code.jquery.com/jquery-1.12.4.min.js"
        integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
        crossorigin="anonymous"></script>

<!-- AngularJS -->
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular.min.js"></script>


<link rel="stylesheet" type="text/css" href="/any/css/uikit.css"/>

<link rel="stylesheet" type="text/css" href="/backshop/css/login.css"/>

</head>

<body>


    <!-- HEADER -->
<div class="headbar">

    <div class="header">

        <!-- LOGO -->
        <h1 class="logo">
            <a href="/">LOGO</a>
        </h1>

        <!--info link -->   
        <div class="headlink">
           <a href="#">&#192; propos</a>
           <a href="#">Aide</a>
        </div>            
        
    </div>
</div>

    <!--login box-->
    <div id="logindiv" class="logindiv">

        

        <!--login-->
        <div id="loginbox" class="loginform">

            <span class="changebox"
                  onclick="changeBox.call(this,'signinbox');">Créer un Compte</span>

            <h1>Connection</h1>

           <form id="loginform" onsubmit="return false;">

            <label>Utilisateur</label>
            <input type="text" class="txt"/>

            <label>Mot de passe</label>
            <input type="text" class="txt"/>

            <!--send form-->
            <div class="sendform">
                <input type="submit" value="Se Connecter"
                       name="submit" class="bt blue-button"/>

                <div class="formload">
                    <span class="icon-load"></span>
                </div>
            </div>
            </form>


        </div>

        <!--sign in-->
        <div id="signinbox" class="loginform" style="display:none">
            <!--<span class="close" onclick="closeBox.call(this);">x</span>-->

            <span class="changebox"
                  onclick="changeBox.call(this,'loginbox');">J'ai un Compte</span>

            <h1>S'inscrire</h1>

           <form id="signinform" onsubmit="return false;">

            <label>Courriel</label>
            <input type="text" class="txt"/>

            <label>Mot de passe</label>
            <input type="text" class="txt"/>
            
            <label>Confirmer le mot de passe</label>
            <input type="text" class="txt"/>

            <!--send form-->
            <div class="sendform">
                <input type="submit" value="S'inscrire"
                       name="submit" class="bt blue-button"/>

                <div class="formload">
                    <span class="icon-load"></span>
                </div>
            </div>
            </form>

        </div>

        <!-- script -->
        <script type="text/javascript">
            function changeBox(divId){
                this.parentNode.style.display = 'none';
                document.getElementById(divId).style.display = 'block';
            }
            
        </script>
       
    </div>

    
<!-- FOOTER -->
<div class="footer">
    <ul>
        <li>&#169;2017&#160; Cheratt Karim</li>
    </ul>
</div>

</body>
</html>