<!DOCTYPE html>
<html>
<head>
<title></title>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<link href='https://fonts.googleapis.com/css?family=Archivo+Narrow:400,700' rel='stylesheet' type='text/css'>

<link rel="stylesheet" type="text/css" href="/any/css/icon.css"/>

<link rel="stylesheet" type="text/css" href="/any/css/frame.css"/>

<link rel="stylesheet" type="text/css" href="/any/css/uikit.css"/>

<!-- jQuery -->
<script src="https://code.jquery.com/jquery-1.12.4.min.js"
        integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
        crossorigin="anonymous"></script>
 

<?php echo $this->headLink(); ?>
<?php echo $this->headScript(); ?>

</head>

<body>

<!-- HEADER -->
<div class="headbar">

    <div class="header">

        <!-- LOGO -->
        <h1 class="logo">
            <a href="/">LOGO</a>
        </h1>

        <!--info link
        <div class="headlink">
           <a href="#">&#192; propos</a>
           <a href="#">Aide</a>
        </div>
        -->
        
        <!--login button--> 
        <?php  if($this->layout()->isConnected) :  ?>
            <div class='login' onclick="alert('todo : go to user space');">
                    Profil
            </div>
        <?php else : ?>
            <div class='login' id="getlogform" >
                Connexion
            </div>
        <?php endif ?>
        
        
    </div>
</div>

    <?php echo $this->content; ?>


<!-- FOOTER -->
<div class="footer">
    <ul>
        <li>&#169;2017&#160; Cheratt Karim</li>
        <!--
        <li>&#169;2017&#160; Compagnie</li>
        <li>&#192; propos</li>
        <li>Vendre</li>
        <li>Acheter</li>
        <li>Conditions d'utilisation</li>
        -->
    </ul>
</div>

    <?php echo $this->loginbox ; ?>


<!--<script type="text/javascript" src="visitor/js/catalogue.js"> </script>-->

    <!-- script
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery.slick/1.5.7/slick.min.js"></script>


    <script type="text/javascript">

    // slick plugin
    $(document).ready(function(){

        // setting
        var prevSpan = document.getElementById('prev-img'),
            nextSpan = document.getElementById('next-img');

        $('.banimg').slick({
            prevArrow: prevSpan,
            nextArrow : nextSpan
        });

    });

    </script>
    -->


</body>
</html>
